apps/vehiculos/urls.py
from django.urls import path
from apps.vehiculos.views import listVehiculos, vehiculosCreate, vehiculosUpdate, vehiculosDelete 

app_name= 'vehiculos'
urlpatterns = [
    path('', listVehiculos, name= 'listvehiculos'),
    path('nuevo/', vehiculosCreate, name= 'vehiculosCreate'),
    path('actualizar/<int:id_vehiculo>/', vehiculosUpdate, name= 'vehiculosUpdate'),
    path('eliminar/<int:id_vehiculo>/', vehiculosDelete, name= 'vehiculosDelete'),
]

apps/ventas/urls.py
from django.urls import path
from apps.ventas.views import listventas, ventasCreate, ventasUpdate, ventasDelete

app_name= 'ventas'
urlpatterns = [
    path('', listventas, name= 'listventas'),
    path('nuevo2/', ventasCreate, name= 'ventasCreate'),
    path('actualizar/<int:id_Venta>/', ventasUpdate, name= 'ventasUpdate'),
    path('eliminar/<int:id_Venta>/', ventasDelete, name= 'ventasDelete'),
]

mdzvehiculos/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.vehiculos.views import home


urlpatterns = [
    path('/', home, name='home'),
    path('admin/', admin.site.urls),
    path('vehiculos/', include('apps.vehiculos.urls', namespace='vehiculos')),
    #path('mantenimiento/', include('apps.mantenimiento.urls', namespace='mantenimiento')),
    path('ventas/', include('apps.ventas.urls', namespace='ventas')),

]

apps/vehiculos/models.py
from django.db import models

# Create your models here.

class Marca(models.Model):
    nombre = models.CharField(max_length=60)

    def __str__(self):
        return self.nombre

class TipoVehiculo(models.Model):
    nombre = models.CharField(max_length=40)

    def __str__(self):
        return self.nombre

class Vehiculo(models.Model):
    modelo = models.CharField(max_length=30)
    color = models.CharField(max_length=20)
    placa = models.CharField(max_length=15)
    motor = models.CharField(max_length=10)
    marca = models.ForeignKey(Marca, null=True, blank=True, on_delete=models.CASCADE)
    tipovehiculo = models.ForeignKey(TipoVehiculo, null=True, blank=True, on_delete=models.CASCADE, verbose_name='Tipo de Vehiculo')

    def __str__(self):
        return self.modelo

apps/ventas/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.vehiculos.models import Vehiculo

# Create your models here.

class Venta(models.Model):
    fecha = models.DateField()
    valorTotal = models.BigIntegerField()
    tipoPago = models.CharField(max_length=20)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    vehiculo = models.ManyToManyField(Vehiculo, through='vehiculoventa')

class vehiculoventa(models.Model):
    vehiculo = models.ForeignKey(Vehiculo, on_delete=models.CASCADE, blank=False, null=False)
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE, blank=False, null=False)
    cantidad = models.IntegerField()
    precio = models.BigIntegerField()

    

apps/vehiculos/views.py
from django.shortcuts import render, redirect
from apps.vehiculos.form import vehiculoForm
from apps.vehiculos.models import Vehiculo

# Create your views here.

def listVehiculos(request):
    vehiculos = Vehiculo.objects.all().order_by('-id')
    context = {'vehiculos': vehiculos}
    return render(request, 'vehiculos/listVehiculos.html',context)

def home(request):
    return render(request, 'base/base.html')

def vehiculosCreate(request):
    if request.method == 'POST':
        form = vehiculoForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('vehiculos:listvehiculos')
    else:
        form = vehiculoForm()
    return render(request, 'vehiculos/vehiculo_form.html', {'form': form})

def vehiculosUpdate(request, id_vehiculo):
    mant = Vehiculo.objects.get(pk=id_vehiculo)

    if request.method == 'GET':
        form = vehiculoForm(instance=mant)
    else:
        form = vehiculoForm(request.POST, instance=mant)
        if form.is_valid():
            form.save()
        return redirect('vehiculos:listvehiculos')
    
    return render(request, 'vehiculos/vehiculo_form.html', {'form': form})

def vehiculosDelete(request, id_vehiculo):
    mant = Vehiculo.objects.get(pk=id_vehiculo)
    if request.method == 'POST':
       mant.delete()
       return redirect('vehiculos:listvehiculos')
    return render(request, 'vehiculos/vehiculosDelete.html', {'vehiculo': mant})

apps/ventas/views.py
from django.shortcuts import render, redirect
from apps.ventas.form import ventaForm
from apps.ventas.models import Venta
 #Create your views here.

def listventas(request):
    venta = Venta.objects.all().order_by('-id')
    context = {'ventas': venta}
    return render(request, 'ventas/listventas.html',context)

def home(request):
    return render(request, 'base/base.html')

def ventasCreate(request):
    if request.method == 'POST':
        form = ventaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('ventas:listventas')
    else:
        form = ventaForm()
    return render(request, 'ventas/venta_form.html', {'form': form})

def ventasUpdate(request, id_Venta):
    mant = Venta.objects.get(pk=id_Venta)

    if request.method == 'GET':
        form = ventaForm(instance=mant)
    else:
        form = ventaForm(request.POST, instance=mant)
        if form.is_valid():
            form.save()
        return redirect('ventas:listventas')
    
    return render(request, 'ventas/venta_form.html', {'form': form})

def ventasDelete(request, id_Venta):
    mant = Venta.objects.get(pk=id_Venta)
    if request.method == 'POST':
       mant.delete()
       return redirect('ventas:listventas')
    return render(request, 'ventas/ventasDelete.html', {'venta': mant})

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https:cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Mendoza</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Inicio
                  <span class="visually-hidden">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'vehiculos:listvehiculos' %}">Vehiculos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'ventas:listventas' %}">Venta</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>


      {% block content %}

      {% endblock %}

      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
</body>
</html>

templates/mantenimiento/listmantenimiento.html
<!--{% extends 'base/base.html' %}

{% block content %}


    <h1 class="pull-right">
        <div class="row">
            <div class="col-4">
                <h3>Listado de Mantenimientos</h3>
            </div>
            <div class="col-4">
                
            </div>
            <div class="col-4">
                <a href="{% url 'mantenimiento:mantenimientoCreate' %}" class="btn btn-primary" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
            </div>
        </div>

    </h1>

        <table class="table table success table-striped">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Fecha</th>
                <th scope="col">Tipo de Mantenimiento</th>
                <th scope="col">Usuario</th>
                <th scope="col">Equipo</th>
            </tr>
            </thead>
            <tbody>
                {% if mantenimiento %}
                    {% for mantenimiento in mantenimiento %}
                        <tr>
                            <td>{{ mantenimiento.id }}</td>
                            <td>{{ mantenimiento.fecha }}</td>
                            <td>{{ mantenimiento.tipomantenimiento }}</td>
                            <td>{{ mantenimiento.user }}</td>
                            <td>{{ mantenimiento.equipo }}</td>
                            <td>
                                <a href="{% url 'mantenimiento:mantenimientoUpdate' mantenimiento.id %}" class="btn btn-warning">
                                    <i class="fa-solid fa-pen"></i>
                                </a>
                                <a href="{% url 'mantenimiento:mantenimientoDelete' mantenimiento.id %}" class="btn btn-danger">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                        <h3>No existen registros</h3>
                {% endif %}
            </tbody>
        </table>

{% endblock %}

templates/mantenimiento/mantenimientoDelete.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <h4>Desea eliminar el registro {{ mantenimiento.name}} ?</h4>
        <button class="btn btn-danger" type="submit">Si, Eliminar</button>
        <a href="{% url 'mantenimiento:listmantenimiento' %}" class="btn btn-primary">Cancelar</a>
    </form>
{% endblock %}

templates/mantenimiento/mantenimiento_form.html
<!--{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Guardar</button>
    </form>
{% endblock %}

templates/vehiculos/listVehiculos.html
{% extends 'base/base.html' %}

{% block content %}


    <h1 class="pull-right">
        <div class="row">
            <div class="col-4">
                <h3>Listado de Vehiculos</h3>
            </div>
            <div class="col-4">
                
            </div>
            <div class="col-4">
                <a href="{% url 'vehiculos:vehiculosCreate' %}" class="btn btn-primary" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
            </div>
        </div>

    </h1>

        <table class="table table success table-striped">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Modelo</th>
                <th scope="col">Color</th>
                <th scope="col">Placa</th>
                <th scope="col">Motor</th>
                <th scope="col">Marca</th>
                <th scope="col">Tipo Vehiculo</th>
               
            </tr>
            </thead>
            <tbody>
                {% if vehiculos %}
                    {% for vehiculo in vehiculos %}
                        <tr>
                            <td>{{ vehiculo.id }}</td>
                            <td>{{ vehiculo.modelo }}</td>
                            <td>{{ vehiculo.color }}</td>
                            <td>{{ vehiculo.placa }}</td>
                            <td>{{ vehiculo.motor }}</td>
                            <td>{{ vehiculo.marca }}</td>
                            <td>{{ vehiculo.tipovehiculo }}</td>
                            <td>
                                <a href="{% url 'vehiculos:vehiculosUpdate' vehiculo.id %}" class="btn btn-warning">
                                    <i class="fa-solid fa-pen"></i>
                                </a>
                                <a href="{% url 'vehiculos:vehiculosDelete' vehiculo.id %}" class="btn btn-danger">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                        <h3>No existen registros</h3>
                {% endif %}
            </tbody>
        </table>

{% endblock %}

templates/vehiculos/vehiculo_form.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Guardar</button>
    </form>
{% endblock %}

templates/vehiculos/vehiculosDelete.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <h4>Desea eliminar el registro {{ vehiculo.name}} ?</h4>
        <button class="btn btn-danger" type="submit">Si, Eliminar</button>
        <a href="{% url 'vehiculos:listvehiculos' %}" class="btn btn-primary">Cancelar</a>
    </form>
{% endblock %}

templates/ventas/listventas.html
{% extends 'base/base.html' %}

{% block content %}


    <h1 class="pull-right">
        <div class="row">
            <div class="col-4">
                <h3>Listado de Ventas</h3>
            </div>
            <div class="col-4">
                
            </div>
            <div class="col-4">
                <a href="{% url 'ventas:ventasCreate' %}" class="btn btn-primary" style="margin-top: -10px; margin-bottom: 5px;">Adicionar</a>
            </div>
        </div>

    </h1>

        <table class="table table success table-striped">
            <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Fecha</th>
                <th scope="col">Valor Total</th>
                <th scope="col">Tipos de Pago</th>
                <th scope="col">Usuarios</th>
            </tr>
            </thead>
            <tbody>
                {% if ventas %}
                    {% for venta in ventas %}
                        <tr>
                            <td>{{ venta.id }}</td>
                            <td>{{ venta.fecha }}</td>
                            <td>{{ venta.valorTotal }}</td>
                            <td>{{ venta.tipoPago }}</td>
                            <td>{{ venta.user }}</td>
                            <td>
                                <a href="{% url 'ventas:ventasUpdate' venta.id %}" class="btn btn-warning">
                                    <i class="fa-solid fa-pen"></i>
                                </a>
                                <a href="{% url 'ventas:ventasDelete' venta.id %}" class="btn btn-danger">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                        <h3>No existen registros</h3>
                {% endif %}
            </tbody>
        </table>

{% endblock %}

templates/ventas/venta_form.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Guardar</button>
    </form>
{% endblock %}

templates/ventas/ventasDelete.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <h4>Desea eliminar el registro {{ vehiculo.name}} ?</h4>
        <button class="btn btn-danger" type="submit">Si, Eliminar</button>
        <a href="{% url 'ventas:listventas' %}" class="btn btn-primary">Cancelar</a>
    </form>
{% endblock %}